server:
  port: 8083
  servlet:
    context-path: /api/v1

spring:
  application:
    name: maintenance-vehicle-health-ingestion
  jackson:
    property-naming-strategy: SNAKE_CASE
    serialization:
      write-dates-as-timestamps: false
